kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lldap-controller
rules:
  - apiGroups:
      - lldap.huizinga.dev
    resources:
      - serviceusers
      - serviceusers/status
      - serviceusers/finalizers
      - groups
      - grours/status
      - grours/finalizers
    verbs:
      - "*"
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
